apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: postgres-standard-pd
provisioner: pd.csi.storage.gke.io
parameters:
  type: pd-standard
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
---
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres
  namespace: ${K8S_NAMESPACE}
spec:
  instances: 3
  bootstrap:
    initdb:
      database: auth_service
      owner: user
      secret:
        name: postgres-app-creds
      postInitSQL:
        - ALTER ROLE "user" CREATEDB
        - CREATE DATABASE config_table_db OWNER "user"
  storage:
    storageClass: postgres-standard-pd
    size: 5Gi
  resources:
    requests:
      cpu: "250m"
      memory: "512Mi"
    limits:
      memory: "512Mi"
