apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres
  namespace: ${K8S_NAMESPACE}
spec:
  instances: 3
  bootstrap:
    initdb:
      database: auth_service
      owner: user
      secret:
        name: postgres-app-creds
      postInitSQL:
        - ALTER ROLE "user" CREATEDB
        - CREATE DATABASE config_table_db OWNER "user"
  storage:
    size: 5Gi
  resources:
    requests:
      cpu: "250m"
      memory: "512Mi"
    limits:
      memory: "512Mi"
